package pm;



import org.semanticweb.owlapi.apibinding.OWLManager;
import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLClass;
import org.semanticweb.owlapi.model.OWLDataFactory;
import org.semanticweb.owlapi.model.OWLDataProperty;
import org.semanticweb.owlapi.model.OWLObjectProperty;

/**
 * Vocabulary class to provide access to the Manchester OWL API representatives for 
 * various entities in the ontology used to generate this code.<p> 
 * 
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: ${javaClass}
 *
 * @version generated on Fri Dec 27 13:22:21 EET 2019 by morningstar
 */

public class Vocabulary {

	private static final OWLDataFactory factory = OWLManager.createOWLOntologyManager().getOWLDataFactory();

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class .<p>
     * 
     */
    public static final OWLClass CLASS_ = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Activity
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ACTIVITY.<p>
     * 
     */
    public static final OWLClass CLASS_ACTIVITY = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Activity"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Analysis_and_Design
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANALYSIS_AND_DESIGN.<p>
     * 
     */
    public static final OWLClass CLASS_ANALYSIS_AND_DESIGN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Analysis_and_Design"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Analysts
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ANALYSTS.<p>
     * 
     */
    public static final OWLClass CLASS_ANALYSTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Analysts"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Analysis_and_Design
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_ANALYSIS_AND_DESIGN.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_ANALYSIS_AND_DESIGN = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Analysis_and_Design"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Business_Modeling
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_BUSINESS_MODELING.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_BUSINESS_MODELING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Business_Modeling"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Configuration_and_Change_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_CONFIGURATION_AND_CHANGE_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_CONFIGURATION_AND_CHANGE_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Configuration_and_Change_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Deployment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_DEPLOYMENT.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_DEPLOYMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Deployment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Environment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_ENVIRONMENT.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_ENVIRONMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Environment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Implementation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_IMPLEMENTATION.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_IMPLEMENTATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Implementation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Project_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_PROJECT_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_PROJECT_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Project_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Requirements
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_REQUIREMENTS.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_REQUIREMENTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Requirements"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Test
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ARTIFACT_TEST.<p>
     * 
     */
    public static final OWLClass CLASS_ARTIFACT_TEST = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Artifact_Test"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Business_Modeling
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class BUSINESS_MODELING.<p>
     * 
     */
    public static final OWLClass CLASS_BUSINESS_MODELING = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Business_Modeling"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Configuration_and_Change_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class CONFIGURATION_AND_CHANGE_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_CONFIGURATION_AND_CHANGE_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Configuration_and_Change_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Deployment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEPLOYMENT.<p>
     * 
     */
    public static final OWLClass CLASS_DEPLOYMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Deployment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Develop_Business_Case
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVELOP_BUSINESS_CASE.<p>
     * 
     */
    public static final OWLClass CLASS_DEVELOP_BUSINESS_CASE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Develop_Business_Case"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Developers
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DEVELOPERS.<p>
     * 
     */
    public static final OWLClass CLASS_DEVELOPERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Developers"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Discipline
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class DISCIPLINE.<p>
     * 
     */
    public static final OWLClass CLASS_DISCIPLINE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Discipline"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Environment
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ENVIRONMENT.<p>
     * 
     */
    public static final OWLClass CLASS_ENVIRONMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Environment"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#General_Roles
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class GENERAL_ROLES.<p>
     * 
     */
    public static final OWLClass CLASS_GENERAL_ROLES = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#General_Roles"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Implementation
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class IMPLEMENTATION.<p>
     * 
     */
    public static final OWLClass CLASS_IMPLEMENTATION = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Implementation"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Managers
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class MANAGERS.<p>
     * 
     */
    public static final OWLClass CLASS_MANAGERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Managers"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#PM_Learning_Material
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PM_LEARNING_MATERIAL.<p>
     * 
     */
    public static final OWLClass CLASS_PM_LEARNING_MATERIAL = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#PM_Learning_Material"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Production_Support
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PRODUCTION_SUPPORT.<p>
     * 
     */
    public static final OWLClass CLASS_PRODUCTION_SUPPORT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Production_Support"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Communications_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_COMMUNICATIONS_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_COMMUNICATIONS_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Communications_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Cost_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_COST_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_COST_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Cost_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Human_Resource_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_HUMAN_RESOURCE_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_HUMAN_RESOURCE_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Human_Resource_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Integration_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_INTEGRATION_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_INTEGRATION_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Integration_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Procurement_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_PROCUREMENT_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_PROCUREMENT_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Procurement_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Quality_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_QUALITY_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_QUALITY_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Quality_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Risk_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_RISK_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_RISK_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Risk_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Scope_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_SCOPE_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_SCOPE_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Scope_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Time_Management
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class PROJECT_TIME_MANAGEMENT.<p>
     * 
     */
    public static final OWLClass CLASS_PROJECT_TIME_MANAGEMENT = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Project_Time_Management"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#RUP_Core_Elements
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class RUP_CORE_ELEMENTS.<p>
     * 
     */
    public static final OWLClass CLASS_RUP_CORE_ELEMENTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#RUP_Core_Elements"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Report_Status
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REPORT_STATUS.<p>
     * 
     */
    public static final OWLClass CLASS_REPORT_STATUS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Report_Status"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Requirements
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class REQUIREMENTS.<p>
     * 
     */
    public static final OWLClass CLASS_REQUIREMENTS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Requirements"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Role
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class ROLE.<p>
     * 
     */
    public static final OWLClass CLASS_ROLE = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Role"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Schedule_and_Assign_Work
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class SCHEDULE_AND_ASSIGN_WORK.<p>
     * 
     */
    public static final OWLClass CLASS_SCHEDULE_AND_ASSIGN_WORK = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Schedule_and_Assign_Work"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Test
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TEST.<p>
     * 
     */
    public static final OWLClass CLASS_TEST = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Test"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Testers
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class TESTERS.<p>
     * 
     */
    public static final OWLClass CLASS_TESTERS = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Testers"));

    /* ***************************************************
     * Class http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Update_Change_Request
     */

    /**
     * A constant to give access to the Manchester OWL api representation of the class UPDATE_CHANGE_REQUEST.<p>
     * 
     */
    public static final OWLClass CLASS_UPDATE_CHANGE_REQUEST = factory.getOWLClass(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#Update_Change_Request"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasBreadthRole
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASBREADTHROLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASBREADTHROLE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasBreadthRole"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasConsult
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASCONSULT.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASCONSULT = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasConsult"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDepthRole
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASDEPTHROLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASDEPTHROLE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDepthRole"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDomain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASDOMAIN.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASDOMAIN = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDomain"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasLearningMaterial
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASLEARNINGMATERIAL.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASLEARNINGMATERIAL = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasLearningMaterial"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasPerform
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASPERFORM.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASPERFORM = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasPerform"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasRecommendation
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRECOMMENDATION.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRECOMMENDATION = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasRecommendation"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasResponsible
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property HASRESPONSIBLE.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_HASRESPONSIBLE = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasResponsible"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isConsultedBy
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISCONSULTEDBY.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISCONSULTEDBY = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isConsultedBy"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isDomainOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISDOMAINOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISDOMAINOF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isDomainOf"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isPerformOf
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISPERFORMOF.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISPERFORMOF = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isPerformOf"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isRecommendedTo
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRECOMMENDEDTO.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRECOMMENDEDTO = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isRecommendedTo"));

    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isResponsibleFor
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the object property ISRESPONSIBLEFOR.<p>
     * 
     */
    public static final OWLObjectProperty OBJECT_PROPERTY_ISRESPONSIBLEFOR = factory.getOWLObjectProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isResponsibleFor"));

    /* ***************************************************
     * Data Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDomain
     */
     
    /**
     * A constant to give access to the Manchester OWL API representation of the data property HASDOMAIN.<p>
     * 
     */
    public static final OWLDataProperty DATA_PROPERTY_HASDOMAIN = factory.getOWLDataProperty(IRI.create("http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDomain"));


}
