package pm.impl;

import pm.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: Default <br>
 * @version generated on Fri Dec 27 13:22:21 EET 2019 by morningstar
 */
public class Default extends WrappedIndividualImpl implements  {

    public Default(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasBreadthRole
     */
     
    public Collection<? extends Role> getHasBreadthRole() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASBREADTHROLE,
                                               DefaultRole.class);
    }

    public boolean hasHasBreadthRole() {
	   return !getHasBreadthRole().isEmpty();
    }

    public void addHasBreadthRole(Role newHasBreadthRole) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASBREADTHROLE,
                                       newHasBreadthRole);
    }

    public void removeHasBreadthRole(Role oldHasBreadthRole) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASBREADTHROLE,
                                          oldHasBreadthRole);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDepthRole
     */
     
    public Collection<? extends Role> getHasDepthRole() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASDEPTHROLE,
                                               DefaultRole.class);
    }

    public boolean hasHasDepthRole() {
	   return !getHasDepthRole().isEmpty();
    }

    public void addHasDepthRole(Role newHasDepthRole) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASDEPTHROLE,
                                       newHasDepthRole);
    }

    public void removeHasDepthRole(Role oldHasDepthRole) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASDEPTHROLE,
                                          oldHasDepthRole);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasDomain
     */
     
    public Collection<? extends Discipline> getHasDomain() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASDOMAIN,
                                               DefaultDiscipline.class);
    }

    public boolean hasHasDomain() {
	   return !getHasDomain().isEmpty();
    }

    public void addHasDomain(Discipline newHasDomain) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASDOMAIN,
                                       newHasDomain);
    }

    public void removeHasDomain(Discipline oldHasDomain) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASDOMAIN,
                                          oldHasDomain);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasLearningMaterial
     */
     
    public Collection<? extends Discipline> getHasLearningMaterial() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASLEARNINGMATERIAL,
                                               DefaultDiscipline.class);
    }

    public boolean hasHasLearningMaterial() {
	   return !getHasLearningMaterial().isEmpty();
    }

    public void addHasLearningMaterial(Discipline newHasLearningMaterial) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASLEARNINGMATERIAL,
                                       newHasLearningMaterial);
    }

    public void removeHasLearningMaterial(Discipline oldHasLearningMaterial) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASLEARNINGMATERIAL,
                                          oldHasLearningMaterial);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasRecommendation
     */
     
    public Collection<? extends PM_Learning_Material> getHasRecommendation() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASRECOMMENDATION,
                                               DefaultPM_Learning_Material.class);
    }

    public boolean hasHasRecommendation() {
	   return !getHasRecommendation().isEmpty();
    }

    public void addHasRecommendation(PM_Learning_Material newHasRecommendation) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASRECOMMENDATION,
                                       newHasRecommendation);
    }

    public void removeHasRecommendation(PM_Learning_Material oldHasRecommendation) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASRECOMMENDATION,
                                          oldHasRecommendation);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isDomainOf
     */
     
    public Collection<? extends Artifact> getIsDomainOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISDOMAINOF,
                                               DefaultArtifact.class);
    }

    public boolean hasIsDomainOf() {
	   return !getIsDomainOf().isEmpty();
    }

    public void addIsDomainOf(Artifact newIsDomainOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISDOMAINOF,
                                       newIsDomainOf);
    }

    public void removeIsDomainOf(Artifact oldIsDomainOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISDOMAINOF,
                                          oldIsDomainOf);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isPerformOf
     */
     
    public Collection<? extends Role> getIsPerformOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISPERFORMOF,
                                               DefaultRole.class);
    }

    public boolean hasIsPerformOf() {
	   return !getIsPerformOf().isEmpty();
    }

    public void addIsPerformOf(Role newIsPerformOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISPERFORMOF,
                                       newIsPerformOf);
    }

    public void removeIsPerformOf(Role oldIsPerformOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISPERFORMOF,
                                          oldIsPerformOf);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isRecommendedTo
     */
     
    public Collection<? extends Artifact> getIsRecommendedTo() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISRECOMMENDEDTO,
                                               DefaultArtifact.class);
    }

    public boolean hasIsRecommendedTo() {
	   return !getIsRecommendedTo().isEmpty();
    }

    public void addIsRecommendedTo(Artifact newIsRecommendedTo) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISRECOMMENDEDTO,
                                       newIsRecommendedTo);
    }

    public void removeIsRecommendedTo(Artifact oldIsRecommendedTo) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISRECOMMENDEDTO,
                                          oldIsRecommendedTo);
    }


}
