package pm.impl;

import pm.*;


import java.net.URI;
import java.util.Collection;
import javax.xml.datatype.XMLGregorianCalendar;

import org.protege.owl.codegeneration.WrappedIndividual;
import org.protege.owl.codegeneration.impl.WrappedIndividualImpl;

import org.protege.owl.codegeneration.inference.CodeGenerationInference;

import org.semanticweb.owlapi.model.IRI;
import org.semanticweb.owlapi.model.OWLOntology;


/**
 * Generated by Protege (http://protege.stanford.edu).<br>
 * Source Class: DefaultReport_Status <br>
 * @version generated on Fri Dec 27 13:22:21 EET 2019 by morningstar
 */
public class DefaultReport_Status extends WrappedIndividualImpl implements Report_Status {

    public DefaultReport_Status(CodeGenerationInference inference, IRI iri) {
        super(inference, iri);
    }





    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#hasRecommendation
     */
     
    public Collection<? extends PM_Learning_Material> getHasRecommendation() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_HASRECOMMENDATION,
                                               DefaultPM_Learning_Material.class);
    }

    public boolean hasHasRecommendation() {
	   return !getHasRecommendation().isEmpty();
    }

    public void addHasRecommendation(PM_Learning_Material newHasRecommendation) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_HASRECOMMENDATION,
                                       newHasRecommendation);
    }

    public void removeHasRecommendation(PM_Learning_Material oldHasRecommendation) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_HASRECOMMENDATION,
                                          oldHasRecommendation);
    }


    /* ***************************************************
     * Object Property http://www.semanticweb.org/morningstar/ontologies/2019/9/untitled-ontology-9#isPerformOf
     */
     
    public Collection<? extends Role> getIsPerformOf() {
        return getDelegate().getPropertyValues(getOwlIndividual(),
                                               Vocabulary.OBJECT_PROPERTY_ISPERFORMOF,
                                               DefaultRole.class);
    }

    public boolean hasIsPerformOf() {
	   return !getIsPerformOf().isEmpty();
    }

    public void addIsPerformOf(Role newIsPerformOf) {
        getDelegate().addPropertyValue(getOwlIndividual(),
                                       Vocabulary.OBJECT_PROPERTY_ISPERFORMOF,
                                       newIsPerformOf);
    }

    public void removeIsPerformOf(Role oldIsPerformOf) {
        getDelegate().removePropertyValue(getOwlIndividual(),
                                          Vocabulary.OBJECT_PROPERTY_ISPERFORMOF,
                                          oldIsPerformOf);
    }


}
